language: java
jdk:
  - oraclejdk7
branches:
  only:
  - "/^v.+/"
  - master
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: tunxtzIX42cv3Qtg7XBLl1E3YZEd5T1ncF4Ez87/RFtW4U5/Zn5rsYGyyAqeMGTZjavU2XLr2GqHDPVFNbZCvjqWFcM3IKTi480oHW9VxdZ62NRsyFYxlNHWgdKMVQqnUZxrIRC5S+IbsZctMHlBcb9jUHZudZcY3+cXB3c8FCitV3Xb8px0lhDxsNWf+M5cj9aWDynxsA7GrYHvZj0OLuRPkQB0H9iVJK05EjyS+gvQ6zX3wfZbIikcY1lfvS6nWo70Sr3dJoQp5Oyu3Meey00ND3487tNlcbj/7JZe0p5mZbCkr+ZhFRPAoLqV/pLQxQoAgA5quaxaBGOI7rsz8VxTb4AZl+cWPB0sOrnwD4SA4G9MM9yU9FKKppEb0ue+BBVo54Q6BpDT+eNv72FTrCNwoCoqC5gKZwqfonI3gzSZkbBcUyF3l3Jsygb3sUGFeLx8EV/ic70BICDmgZJLLb6X2I3iXT+Uux76ECfdd0QcYYaLsU+1ldTuQj2gydDV29tMUGSr7ZkEwFjkBzQnXUCzSJDZvpEXMCAg+JfhOJrXCLDBqHS14G4VMlXNSL81i47AGtmgzipdtsvJNGtq9mTYLJGc5su/8Z8LUDxCwaGczc8f7/QDSP0RvpNwDqwlTEUlCkhYVPQPo+g+0ScBfPy0czgFWlUnUPCodsOI7Ac=
  file: build/libs/XMLSpreadsheetGenerator.jar
  on:
    tags: true
